name: Auto Publisher

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - run: |
          pnpm i
          pnpm run build
          pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          REGISTRY: https://registry.npmjs.org
