name: Beta Publisher

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        options:
          - rc
          - beta
          - alpha

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - name: Build and Run
        run: |
          pnpm i
          pnpm run build
          pnpm publish --tag ${{inputs.tag}} -r --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          REGISTRY: https://registry.npmjs.org
